### ISSUE TITLE
Session Lost after Timeout: restore session state

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-echo-show#145]
## Steps to reproduce

1. Open the browser to a website
2. Wait 5mins - it will time out and take you back to the device homescreen
3. Say "Alexa, reopen Firefox"

### Expected behavior

Option 1: Firefox opens to the website you were viewing
Option 2: Firefox opens to the homescreen overlay with an easy way to get back to the site you were viewing

### Actual behavior

Firefox opens to the homescreen with the URL bar blank and no apparent way to return to the site you were on

### Device information

* Echo Show device (1st gen? 2nd?): 2nd
* Firefox version: 1.2

### Considerations

This came from a review, here's the exact use case:
" I opened up the browser to a recipe site and started cooking dinner. After a couple minutes, the device times out and returns to the home screen! "Alexa, reopen my browser" should get me back to the page I was on right? No! It takes me back to the home page and I have to navigate to the recipe again. Rinse and repeat every two minutes until I give up and open up a physical cookbook."

**Comment by mcomella** [comment]
Note: Firefox session state is not lost when opening skills e.g. "Echo, what's the weather?"

Firefox session state is lost when opening Silk (another app, as opposed to skill) but that could be because it's too resource intensive to have both Silk and Firefox open.

---

I confirmed on device that the process is killed when firefox is backgrounded. In order to restore state after backgrounding, we either need to:
1. Request to Amazon that we can stay in memory for some duration (like stock Android)
1. Save the data to disk and restore it on start.
  - This would force users to reload the page every time they reopen Firefox and readjust their scroll position (we may be able to save that too...)
  - Silk does this but only restores the last page you were on, not the whole back stack
  - Restoring the back stack may not be possible because WebView is expecting to store/restore the state and it may only be able to handle data from memory

I'd prefer option 1 because it keeps us standard with our behavior on stock Android and doesn't force users to reload the page.

An alternative is that we can provide users the option to keep the screen on #146 and then we don't need to handle this case.

@athomasmoz Do you think it's appropriate to request Amazon to change their timeout behavior so that our app can stay open in the background for some duration so users can restore their session?

**Comment by athomasmoz** [comment]
Thanks for checking this out.

This ticket was added to our sprint as a way to lessen the pain for users who keep getting timed out in the middle of a task (ie. going through a recipe), while we wait for Amazon to hopefully increase the timeout. So at least if they get timed out, they can reopen the browser and return to their task. 

I think option 1 is a good idea in general, but I'm worried about blocking this issue on it. I think the best thing we can do is make a strong case to Amazon about the problem and then work with them on timing for a solution. If they aren't able to address one of the issues soon (timeout or restoring session), then we can look at option 2.

As a first step, let's grab data to support our case. Do you know if we can get numbers on:
- How often the timeout occurs
- How often the app is reopened within 5mins of closing it

**Comment by mcomella** [comment]
N.B.: we don't receive the `onStop` callback when the screen times out – #172. This might be why session restoration is not working in the first place.

**Comment by mcomella** [comment]
Result of the initial discussion with athomas and Felix: we understand users whose last interactions with our current UI probes (i.e. browser chrome) was five minutes before the session ends but do not understand users who interacted with the browser five minutes before the session ends. We want to add a probe to understand these users. Due to implementation complexities, we will ignore users who are watching videos that are not interacting via touch but whose timeout is delayed (to 8 hours, provided a video keeps playing) by watching videos.

Action items:
- Add telemetry probe that triggers 4.5 minutes after last touch event
  - The analysis will see if the session ends ~30s after that probe, then we can understand the behavior of users who interacted with page content before the timeout
- If data shows this is a common use case, attempt to restore sessions
- If data shows this is a common use case, ask Amazon about better session restoration mechanisms and increased timeouts

**Comment by mcomella** [comment]
Spoke with Felix and athomas: we discovered we could use "session end in one process and start in another" as a heuristic for timeouts and we quantitatively, the fraction of timeouts where users open a session soon after is not large. However, what we really want to identify is what fraction of users are affected by this, rather than the fraction of timeouts. The best way to do this is anecdotally (e.g. surveys) or standins. Waiting on @athomasmoz to decide which path we want to take.

**Comment by athomasmoz** [comment]
Closing issue off. Felix has done investigation and not found evidence to prove our hypothesis that this is an issue affecting a significant number of users.

We have decided to run tests to determine if restoring session is a preferred experience to starting the browser fresh each time.
