### ISSUE TITLE
Restore Last URL

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-echo-show#186]
### Why/User Benefit/User Problem

When I re-open Firefox a few minutes after using it, I want the last page I visited to be restored, so I can pick up where I left off.

This will address cases when:
* Unwanted timeout occurs (ie. when following a recipe)
* A user is multi-tasking and exits the app

### What / Requirements

* Last URL is restored when a user re-opens the browser within 5minutes of closing

### Success Criteria

Success means restoring a page the user wants to see. To confirm we have succeeded, we should track how often the users stays on the site (can be measured by how often the user doesn't open menu or enter value into the URL bar within 30s of opening the browser with the restored page)

To ensure we have not hurt the experience, we should monitor reviews for any feedback that suggests the users can't get to their pinned tiles. The potential negative effect of this change is that we aren't showing pinned tiles straight away, so users need to know how to bring the menu up.

**Comment by mcomella** [comment]
QA: I refactored the code for how we handle Intents (i.e. launch the app) so we may want to go over those use cases more closely.

**Comment by mcomella** [comment]
@athomasmoz I discovered one flaw in this approach: to open Firefox again, users have four commands at their disposal:
- "Open Firefox"
- "Open youtube/bing/google"

If they're unfamiliar with the "Firefox" command, they'll request the other commands which will put a new page at the top of their stack instead of the previous URL.

Some solutions if a non-"Open firefox" command is issued when we would otherwise restore the URL:
- Add telemetry to understand how often we're opened with "Open Firefox" or "Open youtube/bing/google": see if this is even an issue. Note that we'll probably want to know this if we add telemetry for how often sessions are restored too
- Travel to the new page but provide a new temporary (show for 20s?) button that, when clicked, brings users to the restored page instead
- Prompt the user to select "restore" or "load" page (this is pretty bad because it'd be jarring to users who really meant to travel to these other pages)

---

@athomasmoz Relatedly, do we want add telemetry to how often sessions are restored?

**Comment by mcomella** [comment]
@athomasmoz Another issue: users may be accustomed to their session not restoring when the app is closed: are we concerned how users might perceive this change if they leave a session open they didn't intend for others to see? (I guess we have no "private browsing" guarantees in the first place)

**Comment by mcomella** [comment]
QA: if the app times out, we should restore the last url if the user reopens the app within five minutes, i.e.:
- Open app
- Wait five minutes for time out
- Open app within five minutes

Expected: Session is restored

Please test this and consider adding a test case for it.
