### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Tukks** [mozilla-mobile/firefox-echo-show#279]
Last commit is 2 month ago, 2 PR are waiting, 2019 Q1 Prioritized Feature List is late.
Did I miss something?

Thank you

**Comment by mcomella** [comment]
The team maintains two products – this and Firefox for Fire TV – and we're focused on a new feature for Firefox for Fire TV right now.

@Tukks Is there a specific problem you have as a user or specific functionality you're looking for?

**Comment by Tukks** [comment]
Ok thank you for the quick response, I understand.
this on seem important to watch netflix for example on the echo show (maybe also some tweak on user agent to trick some website, or possibility to put wherever user agent I want)
https://github.com/mozilla-mobile/firefox-echo-show/issues/200

**Comment by mcomella** [comment]
Thanks for the feedback! fwiw, we tried to get Netflix to work in #88 by using a user agent (I updated the issue with some of our analysis): when we tried it, unfortunately the desktop site is slow on the device and playing video content crashed due to a bug in WebView. We want it to work, however, so we'll keep your feedback in mind and keep at it.
