### ISSUE TITLE
Web page text is tiny on smaller devices

### ISSUE THREAD

**Issue by devinreams** [mozilla-mobile/firefox-echo-show#284]
In addition to #36 we have reports the text is likely too small on smaller devices such as the Echo Show 5.

### User Problem
When you load a page with a lot of text (e.g. wikipedia)
Text should be readable from a distance (7-foot device)
But, right not the text is tiny and unreadable

### Acceptance Criteria

* Default font size for website is X, which is readable from 3-feet on gen 3
* Font size for 2nd gen & 1st gen are not changed

### Output

* Default font size for websites is scaled to 300%
* Documentation on zooming options
* Screenshots to share with others, who don't have the device

### Notes

There are several "text scaling" and "text zoom" methods we can try to fix this.

**Comment by liuche** [comment]
There are some WebView APIs (zoom, minimum font size, etc) - will probably have to go through WV methods, try it on some sites, make suggestions to @athomasmoz.

**Comment by Baron-Severin** [comment]
@athomasmoz I did some investigation into this, and found three main options (`defaultFontSize`, `textZoom`, and `setInitialScale`).  None are without flaws, but I definitely have a preference.

These pictures are all on the new ES 5.

This is what master looks like, on our three starting tiles + some recipe site I found:

## Master (for reference)
![MASTER-google-search](https://user-images.githubusercontent.com/13170306/61418397-38f78700-a8af-11e9-96ce-149dee57d5dd.png)

--------------
![MASTER-youtube](https://user-images.githubusercontent.com/13170306/61418399-39901d80-a8af-11e9-81c9-9414d946fea0.png)


--------------
![MASTER-wikipedia](https://user-images.githubusercontent.com/13170306/61418398-38f78700-a8af-11e9-9f67-6a0a3fb08d51.png)

--------------
#### Bon Appetit - after load
![MASTER-bon-appetit](https://user-images.githubusercontent.com/13170306/61418396-38f78700-a8af-11e9-95c3-0e37b6bd396a.png)

--------------
#### Bon Appetit - scrolled down to body text
![MASTER-bon-appetit-body](https://user-images.githubusercontent.com/13170306/61418427-4ad92a00-a8af-11e9-9310-178732192ecd.png)

--------------
### Next to a whiteboard marker, for context (text is really, really small)
![IMG_20190717_162024](https://user-images.githubusercontent.com/13170306/61418683-203ba100-a8b0-11e9-9e28-9bc2e7b5dfac.jpg)

--------------
## defaultFontSize
This is really a suggestion that sites are free to disobey (in this group, it only affected Wikipedia).  It also has the drawback that there's no easy way for the user to change it, if a site renders badly because of it (always a possibility when we decide to change how sites are displayed).

![DEFAULT-FONT-SIZE-google-search](https://user-images.githubusercontent.com/13170306/61418767-73155880-a8b0-11e9-85f4-bd77546d4b1b.png)

--------------
![DEFAULT-FONT-SIZE-youtube](https://user-images.githubusercontent.com/13170306/61418769-73adef00-a8b0-11e9-96e0-2c7169a480e4.png)

--------------
![DEFAULT-FONT-SIZE-wikipedia](https://user-images.githubusercontent.com/13170306/61418768-73adef00-a8b0-11e9-9581-0e9aef263dad.png)

--------------
![DEFAULT-FONT-SIZE-bon-appetit-load](https://user-images.githubusercontent.com/13170306/61418766-73155880-a8b0-11e9-8478-13ceb883bb1c.png)

--------------
![DEFAULT-FONT-SIZE-bon-appetit-body](https://user-images.githubusercontent.com/13170306/61418765-73155880-a8b0-11e9-80b1-9f5699720cd2.png)

--------------
## textZoom
This worked in more places, but also seems to break a lot of layouts when increased by this much (story specifies 3x).  It shares the drawback of not being easily changed by the user, unless we want to spend time exposing a custom feature to do so.

![TEXT-ZOOM-google-search](https://user-images.githubusercontent.com/13170306/61418880-eb7c1980-a8b0-11e9-9f3e-83e13d617ed1.png)

--------------
![TEXT-ZOOM-youtube](https://user-images.githubusercontent.com/13170306/61418882-eb7c1980-a8b0-11e9-8af3-0bda4f190a3b.png)

--------------
![TEXT-ZOOM-wikipedia](https://user-images.githubusercontent.com/13170306/61418881-eb7c1980-a8b0-11e9-86d1-0f77144b25bc.png)

--------------
![TEXT-ZOOM-bon-appetit-load](https://user-images.githubusercontent.com/13170306/61418879-eb7c1980-a8b0-11e9-837c-23a1795b74ea.png)

--------------
## !!!
`Note that reading this text would require scrolling right and left`
## !!!
![TEXT-ZOOM-bon-appetit-body](https://user-images.githubusercontent.com/13170306/61418878-eae38300-a8b0-11e9-89ca-c53f4a0ab5ee.png)

--------------
## setInitialScale
This seemed to work the best out of the three, although it's not without problems (see Wikipedia).  All it does is change the initial zoom level, so the user is free to pinch back to whatever setting required.  I find this to be a strong positive, because it fits in with already familiar usage patterns.  In most cases this doesn't change the content of the website, although it sometimes appears to bucket us into a smaller MediaQuery.  In the instances I observed, this wound up being a good thing, as you'll see.

--------------
### Google search on load
![INITIAL-SCALE-google-search-load](https://user-images.githubusercontent.com/13170306/61419070-7eb54f00-a8b1-11e9-9219-7bf80be9050b.png)

--------------
### Google search after scrolling down
![INITIAL-SCALE-google-search-body](https://user-images.githubusercontent.com/13170306/61419069-7eb54f00-a8b1-11e9-829b-69b810cb3763.png)

--------------
### Wikipedia on load
![INITIAL-SCALE-wikipedia-load](https://user-images.githubusercontent.com/13170306/61419071-7eb54f00-a8b1-11e9-8acb-df8d99ab132b.png)

--------------
### Wikipedia after scrolling
![INITIAL-SCALE-wikipedia-moved](https://user-images.githubusercontent.com/13170306/61419072-7eb54f00-a8b1-11e9-982e-c7712debbd62.png)

--------------
![INITIAL-SCALE-youtube](https://user-images.githubusercontent.com/13170306/61419073-7f4de580-a8b1-11e9-923c-29b50f7c62a6.png)

--------------
![INITIAL-SCALE-bon-appetit-load](https://user-images.githubusercontent.com/13170306/61419068-7eb54f00-a8b1-11e9-818e-526736c55e07.png)

--------------
![INITIAL-SCALE-bon-appetit-body](https://user-images.githubusercontent.com/13170306/61419066-7e1cb880-a8b1-11e9-8402-d0644f34051f.png)

--------------

**Comment by athomasmoz** [comment]
Thanks @Baron-Severin , and I agree the setInitialScale looks the best. I really like that the user can pinch to change zoom on it. Does it have any negative effects when viewing YouTube? If not, I think it makes sense to go with that one. This will be much easier for users to read!

**Comment by Baron-Severin** [comment]
@athomasmoz it seems to bucket us into a mobile layout (I think before we might have been in tablet?) on YouTube.  To be honest, I think it looks a lot better.  Would you like this change made on the ES5 only, or all devices?  I could take pictures of how it looks if that would help (or send you an APK if you'd like to try for yourself).

**Comment by athomasmoz** [comment]
Thanks! Let me know if you have follow-up questions I can help with?

**Comment by Baron-Severin** [comment]
@brampitoyo I worked with @mcomella on this, and we had a few thoughts that we wanted to fill you in on.  We eventually settled on setting an initial zoom level of 150%, combined with a minimum text size of 14 (default is 8)

Concerns we had
- Zooming buckets users into mobile designs on many sites
  - This is usually helpful, but when this happens the user can't "zoom out" to go to the other design
- Increasing font size can frequently break layouts
  - Devs test their layouts with their own sizes
  - We chose to be conservative with minimum text size increases for this reason
  - Small text looks like a page is too small for the device.  A broken website looks like Firefox is broken
- By combining these two approaches, we were able to make smaller changes to each
  - Hopefully this will preserve the original intent of most websites

**Comment by brampitoyo** [comment]
@Baron-Severin Sorry, I had missed your progress on this issue completely!

Combining initial zoom level and minimum text size is a clever approach. I agree that we will achieve a balance of readability and CSS layout compatibility with that.

We also may want to think about increasing sizes on the 1st gen Echo Show, so texts don’t look too small when compared to the 2nd gen. I’m not sure if it’s necessary, but we might as well think about it while we’re thinking about Echo Show 5?

Here’s what the scaling may look like (sorted by device screen size):

| Generation | Screen size | Initial zoom level | Minimum text size |
| --- | --- | --- | --- |
| 2nd (baseline) | 10.1″ | 100% | 8 |
| 1st | 7″ | Suggest 120–125% | Suggest 10–11 |
| 3rd | 5″ | 150% | 14 |

**Comment by Baron-Severin** [comment]
@brampitoyo It might be worth looking at, but to be honest I'm very hesitant to adjust these where we can avoid it.  It's pretty necessary on the ES5, but even small tweaks are going to break some pages.  My big concern is that if a user sees text that's too small, they'll think "this device is too small," but if they see a broken layout (that's not broken on other devices) they'll think "Firefox is broken."

My preferred solution would be to expose a slider to the user that would let them adjust these values themselves.  I think that would make it clear that we weren't breaking the pages.

**Comment by brampitoyo** [comment]
@Baron-Severin Sounds good. Then let’s stick with only adjusting the default values on the Echo Show 5.

**Comment by mcomella** [comment]
>
>  My preferred solution would be to expose a slider to the user that would
> let them adjust these values themselves.


Should we file a bug for this?

**Comment by brampitoyo** [comment]
@mcomella @Baron-Severin filed #298.

**Comment by kglazko** [comment]
Device: Echo Show 5 (SF Office)
Status: Verified
Sites verified:
- Wikipedia.com
- Blogs at Scientific American
- LinuxJournal.com
- Macys.com
- Utcc.utoronto.ca/~cks/space/blog/unix/NoSwapConsequence
- Medium.com
- CDC.gov

**Comment by brampitoyo** [comment]
@kglazko Thanks for verifying!

Do you think it’s worth it (if we’re able) to run a test suite and get screenshots from top sites? Just to be extra sure that we haven’t encountered any corner case.
