### ISSUE TITLE
Update CCPA compilance

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-echo-show#320]
https://docs.google.com/document/d/1s_E-hmmwg95pLTZf-dB9ZV8zkg_bGqayeTW20BI7fk4/edit

- Upgrade AC 24+
- Integrate Glean
- Add legacy ping to glean metric
- Add telemetry id to legacy ping

**Comment by Dexterp37** [comment]
As [suggested over Riot](https://matrix.to/#/!SCdsJdSTaQHjzEVrAE:mozilla.org/$AL2jRtIa3Ar2xVVZG00h7m-QH7ocJ6-zfX8ZpdjEPQ0?via=mozilla.org&via=t2bot.io), for this specific case it might be helpful to pursue a different path: using Glean outside of Android Components.

**Why does Mozilla consume Glean through A-C?**
Because every version of A-C guarantees that all the components it includes work well and are tested with each other, so that you don't need to expect compatibility issues.

**Is it possible to use Glean outside of A-C?**
Yes, it is, but care should be taken in doing that. Instead of depending on Glean as described in [our docs](https://mozilla.github.io/glean/book/user/adding-glean-to-your-project.html), one could do as we currently do in [`service-glean`](https://github.com/mozilla-mobile/android-components/blob/8ce4bdb1870b45ac649196be361af743f5016b4f/components/service/glean/build.gradle#L42-L43), by directly importing the Glean SDK.
